# Generated by Django 3.0.9 on 2020-08-08 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f5_date', models.DateField()),
                ('act_title', models.TextField()),
                ('act_time', models.TimeField(default='00:00:00')),
                ('founder', models.CharField(max_length=10)),
                ('location', models.TextField()),
                ('minimum', models.IntegerField(default=1)),
                ('maximum', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f5day.Activity')),
            ],
        ),
    ]
